### ISSUE TITLE
Tensorflow-directml doesnt work with AMD Radeon RX 6700 XT

### ISSUE THREAD

**Issue by tensorrpi** [microsoft/tensorflow-directml#254] opened 2021-05-24 08:36 UTC
Host System
--------------------------------------------------------------------------------
Windows 10 Version  : Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Processor           : AMD Ryzen 5 5600X 6-Core Processor              (12 CPUs), ~3.7GHz
Memory              : 16384MB RAM
DirectX Version     : DirectX 12

Python Environment
--------------------------------------------------------------------------------
Python Version      : 3.6.13
TensorFlow-DirectML : 1.15.5.dev210429

DirectX Device
--------------------------------------------------------------------------------
Description         : AMD Radeon RX 6700 XT
Manufacturer        : Advanced Micro Devices, Inc.
Chip Type           : AMD Radeon Graphics Processor (0x73DF)
Dedicated Memory    : 12243 MB
Driver Version      : 27.20.21003.8013
Driver Model        : WDDM 2.7
Driver Date         : 11.05.2021 02:00:00
Feature Levels      : 12_1,12_0,11_1,11_0,10_1,10_0,9_3,9_2,9_1

# Repro Details

I am trying to run inference using Tensorflow SSD MobilenetV2 but it doesnt work:
`python detect_realtime_nano.py --trt-graph ssd_mobilenet_v2_coco_2018_03_29\frozen_inference_graph.pb --labels mscoco_label_map.pbtxt`

This is the terminal output:
```
[INFO] loading TRT graph...
WARNING:tensorflow:From C:\Users\bukar\tensorflow1\project2\detect_realtime_nano.py:26: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From C:\Users\bukar\tensorflow1\project2\detect_realtime_nano.py:28: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

[INFO] initializing TensorFlow session...
WARNING:tensorflow:From C:\Users\bukar\tensorflow1\project2\detect_realtime_nano.py:97: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From C:\Users\bukar\tensorflow1\project2\detect_realtime_nano.py:99: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

[INFO] starting video stream...
[INFO] warming up the nano...
2021-05-24 10:10:51.758549: F tensorflow/core/common_runtime/dml/dml_heap_allocator.cc:103] Check failed: ptr != nullptr Invalid pointer
2021-05-24 10:10:51.758616: F tensorflow/core/common_runtime/dml/dml_heap_allocator.cc:103] Check failed: ptr != nullptr Invalid pointer
```

Same script worked fine using tensorflow-CPU-version. Atached: The python-script as txt-file.
[detect_realtime_nano_py.txt](https://github.com/microsoft/tensorflow-directml/files/6530924/detect_realtime_nano_py.txt)

I just downloaded the SSD-Model and try running inference using a USB-Webcam.
What could be the problem?

**Comment by jstoecker** [comment] 2021-05-24 10:24
Do you have more detailed steps to set up your repro? The script you attached imports some dependencies (e.g. `object_detection`) and you also passed in some arguments like the .pb file and .pbtxt file. We'll need these same files to run your script.

Have you tried running any other TF models/scripts?

Thanks!

**Comment by tensorrpi** [comment] 2021-05-24 11:51
The script uses the method "create_category_index_from_labelmap" from the Tensorflow Object Detection API. I am using the MobilenetV2-model from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf1_detection_zoo.md and the Labelmap 
[mscoco_label_map_pbtxt.txt](https://github.com/microsoft/tensorflow-directml/files/6532073/mscoco_label_map_pbtxt.txt) (uploaded as txt because otherwise not supported).
I also tried to run a training script using InceptionV2 and got the same error.
Same scripts on the same PC worked fine using tensorflow-CPU-version.
What would be the recommended way to run pretrained SSD-MobilenetV2 inference with USB-Webcam using Tensorflow-directml?

**Comment by jstoecker** [comment] 2021-05-24 19:06
Thanks. I'm able to repro this now. The issue is not specific to your graphics card.

I can't run this using `tensorflow-gpu` with CUDA either, but it could just be a coincidence. This is with a discrete NVIDIA GPU that has 8GB of memory:

```
2021-05-24 11:35:28.248310: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 2.91G (3123724288 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
```

I can only run this with tensorflow-cpu. I haven't tried debugging yet but I'll get back to you when I have the time to look into this a bit more. 

Until we've taken a deeper look I can't recommend how to run this specific model with tensorflow-directml. If you're simply interested in a pretrained object detection model with webcam input you can try the [YOLOv3 sample here](https://github.com/microsoft/DirectML/tree/master/TensorFlow/yolov3).

**Comment by tensorrpi** [comment] 2021-05-24 19:50
Thank you for the answer.
I also tried the Yolov3 sample and the inference worked fine.
But when I tried to run the training script from the sample, I always got a driver crash, even with a batch size of 1.

**Comment by jstoecker** [comment] 2021-06-10 00:46
This was caused by a bug in one of our kernels and will be fixed in the next release. Thanks for reporting this!

**Comment by PatriceVignola** [comment] 2021-09-09 21:15
The latest tensorflow-directml package on pypi should resolve this issue.

**Closed as completed by PatriceVignola** 2021-09-09 21:15 UTC
